### ISSUE TITLE
memory leak occurs when no index is registered on get(path).

### ISSUE THREAD

**Issue by shinnya** [namusyaka/r2ree#2]
https://github.com/namusyaka/r2ree/blob/7764fbda03c22d61250d38a5da0e5ddb7c394567/src/r2ree.cc#L172

At  the line, you must free `params` object. When the size of `root->indices` is zero and `path` is "/" (i.e. non-empty string), you leaks memory.

You can reproduce the issue by the following code:

```cpp
#include "r2ree.hh"

int main(int argc, char **argv)
{
  using namespace std;
  r2ree::radix_tree *tree = new r2ree::radix_tree();
  auto result = tree->get("/");
  delete[] std::get<2>(result).params;
  delete tree;
}
```

Use valgrind to see for more detail like the following:

```bash
$ valgrind --leak-check=full /path/to/executable
```

It seems that https://github.com/namusyaka/r2ree-ruby/blob/39b1c8e647732de1ebce05dd70b8a1903e1d81ec/ext/r2ree/r2ree.cc#L31 also leaks memory because you forget to free allocated memory.

**Comment by namusyaka** [comment]
@shinnya Could you send a patch?
